apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-delete-tasks
spec:
  ingressClassName: {{ .Values.deleteTask.ingress.ingressClass }}
  rules:
    - host: {{ .Values.deleteTask.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-delete-tasks
                port:
                  number: {{ .Values.deleteTask.ServicePort }}
