apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-add-tasks
spec:
  replicas: {{ .Values.addTask.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-add-tasks
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-add-tasks
    spec:
      containers:
      - name: {{ .Release.Name }}-add-tasks
        image: "{{ .Values.common.containerRegistryURL }}/{{ .Values.addTask.image.name }}:{{ .Values.addTask.image.tag }}"
        ports:
        - containerPort: {{ .Values.addTask.port }}
        env: 
        - name: CONNECTION_STRING
          value: "{{ .Values.addTask.connectionString }}"        
