apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-update-tasks
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-update-tasks
  ports:
    - port: {{ .Values.getTask.ServicePort }}
      targetPort: {{ .Values.getTask.port }}
